config/routes.rb
Rails.application.routes.draw do
  resources :firsts do
    resources :seconds
  end

  root 'firsts#index'

end

app/models/first.rb
class First < ActiveRecord::Base
  has_many :seconds
end

app/models/second.rb
class Second < ActiveRecord::Base
  belongs_to :first
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/firsts_controller.rb
class FirstsController < ApplicationController
  before_action :set_first, only: [:show, :edit, :update, :destroy]

  # GET /firsts
  # GET /firsts.json
  def index
    @firsts = First.all
  end

  # GET /firsts/1
  # GET /firsts/1.json
  def show
    @seconds = @first.seconds.all
    @second = @first.seconds
  end

  # GET /firsts/new
  def new
    @first = First.new
  end

  # GET /firsts/1/edit
  def edit
  end

  # POST /firsts
  # POST /firsts.json
  def create
    @first = First.new(first_params)

    if @first.save
      redirect_to @first, notice: 'First was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /firsts/1
  # PATCH/PUT /firsts/1.json
  def update
    if @first.update(first_params)
      redirect_to @first, notice: 'First was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /firsts/1
  # DELETE /firsts/1.json
  def destroy
    @first.destroy

    redirect_to firsts_url, notice: 'First was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_first
    @first = First.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def first_params
    params.require(:first).permit(:body)
  end
end

app/controllers/seconds_controller.rb
class SecondsController < ApplicationController
  before_action :set_second, only: [:show, :edit, :update, :destroy]

  # GET /seconds
  # GET /seconds.json
  def index
    @seconds = Second.all
  end

  # GET /seconds/1
  # GET /seconds/1.json
  def show
  end

  # GET /seconds/new
  def new
    @first = First.find(params[:first_id])
    @second = @first.seconds.new
  end

  # GET /seconds/1/edit
  def edit
  end

  # POST /seconds
  # POST /seconds.json
  def create
    @first = First.find(params[:first_id])
    @second = @first.seconds.build(second_params)

    if @second.save
      redirect_to @first, notice: 'Second was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /seconds/1
  # PATCH/PUT /seconds/1.json
  def update
    if @second.update(second_params)
      redirect_to @second, notice: 'Second was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /seconds/1
  # DELETE /seconds/1.json
  def destroy
    @second.destroy

    redirect_to @first, notice: 'Second was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_second
    @first = First.find(params[:first_id])
    @second = @first.seconds.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def second_params
    params.require(:second).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firsts_helper.rb
module FirstsHelper
end

app/helpers/second_helper.rb
module SecondHelper
end

app/views/firsts/_form.html.erb
<%= form_for(@first) do |f| %>
  <% if @first.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@first.errors.count, "error") %> prohibited this first from being saved:</h2>

      <ul>
      <% @first.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body, 'Title' %><br>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit 'Create How To' %>
  </div>
<% end %>

app/views/firsts/edit.html.erb
<h1>Editing How To</h1>

<%= render 'form' %>

<%= link_to 'Show', @first %> |
<%= link_to 'Back', firsts_path %>

app/views/firsts/index.html.erb
<h1>Listing How To's</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firsts.each do |first| %>
      <tr>
        <td><%= first.body %></td>
        <td><%= link_to 'Show', first %></td>
        <td><%= link_to 'Edit', edit_first_path(first) %></td>
        <td><%= link_to 'Destroy', first, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New How To', new_first_path %>

app/views/firsts/new.html.erb
<h1>New How To</h1>

<%= render 'form' %>

<%= link_to 'Back', firsts_path %>

app/views/firsts/show.html.erb
<p id="notice"><%= notice %></p>
<h3><%= @first.body %></h3>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% n = 1 %>
    <% @seconds.each do |second| %>
      <tr>
        <td><%= n %></td>
        <td><%= second.body %></td>
        <td><%= link_to 'Show', first_second_path(@first, second) %></td>
        <td><%= link_to 'Edit', edit_first_second_path(@first, second) %></td>
        <td><%= link_to 'Destroy', first_second_path(@first, second), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% n += 1 %>
    <% end %>
  </tbody>
</table>
<div>
  <%= link_to 'New Task', new_first_second_path(@first) %> |
  <%= link_to 'Back', firsts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/seconds/_form.html.erb
<%= form_for([@first, @second]) do |f| %>
  <% if @second.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@second.errors.count, "error") %> prohibited this second from being saved:</h2>

      <ul>
      <% @second.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body, 'Task' %><br>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Task' %>
  </div>
<% end %>

app/views/seconds/edit.html.erb
<h1>Editing first</h1>

<%= render 'form' %>

<%= link_to 'Show', first_second_path %> |
<%= link_to 'Back', @first %>

app/views/seconds/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', @first %>

app/views/seconds/show.html.erb
<p id="notice"><%= notice %></p>
<h3><%= @second.body %></h3>
<%= link_to 'Back', first_path(@first) %>